### ISSUE TITLE
Large union types generated

### ISSUE THREAD

**Issue by jpbow** [octoshikari/aidbox-tool#172]
**Describe the bug**
Large (many thousands of lines) of union types are generated in the Typescript definition file, see screenshot for example in the generated `DocumentReference` interface.

**Expected behavior**
Simply have `string` as the type instead. Will significantly reduce the size of the file too as there are quite a few of these in there.
e.g. line 127 in the below screenshot code would become: `'type'?: string;`

**Screenshots**
<img width="1576" alt="Screenshot 2023-01-04 at 9 36 57 AM" src="https://user-images.githubusercontent.com/5476177/210437772-284a9e2d-262f-4ae4-89c9-91470430e37e.png">

**Comment by octoshikari** [comment]
Hi @jpbow. I added few args for generator subcommand. It will use just `string` as type for large unions and you can provide  values max count
