### ISSUE TITLE
Generate valid values for provided resource

### ISSUE THREAD

**Issue by M1kEk1M** [octoshikari/aidbox-tool#21]
**Is your feature request related to a problem? Please describe.**
There is a lot of cases when you need some generated data - autotesting, manual testing, prepared data when doing some kind of UI on top of box, maybe even some load testing.

**Describe the solution you'd like**
Some tool to generate values by provided resource. For example it could look like
```
box generate appointment
```
And appointment with all related required fields will be generated. And maybe when providing some additional info (with params?) it may create optional fields, like
```
box generate appointment --withOptionalOne --withOptionalTwo
```
or somehing equivalent.

I suggest it should return resource ID on completion.

**Describe alternatives you've considered**
https://github.com/synthetichealth/synthea. That solution can generate proper FHIR values, but if we extend schema with zen synthea will obviously not take that changes into account

**Comment by octoshikari** [comment]
I think we can start with common resources like Patient, Appointment, Encounter
